/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;
import java.util.Random;

public class App {
    
    void heads(double[] pValues, int[] nValues, int trials)
    {
        for(int i=0; i < pValues.length; i++){
            double p = pValues[i];

            for(int j=0; j < nValues.length; j++){
                int n = nValues[j];
                int totalHeads = 0;

                for(int trial=0; trial < trials; trial++){
                    int headsPerTrial = 0;

                    for(int flip=0; flip < n; flip++){
                        if(Math.random() < p){
                            headsPerTrial++;
                        }
                    }
                    totalHeads += headsPerTrial;
                }

                double headsAverage = (double) totalHeads / trials;
                double headsExpected = n * p;

                System.out.printf("p: %.2f, n: %d, avg heads: %.2f, expected: %.2f%n", p, n, headsAverage, headsExpected);
            }
        }
    }

    public static void main(String[] args) {
        double[] pValues = {0.5, 0.75, 0.9};
        int[] nValues = {10, 100, 200, 500, 1000};
        int trials = 10;

        App app = new App();
        app.heads(pValues, nValues, trials);
    }
}
